# This is a basic workflow to help you get started with Actions

name: package-kicad-plugin

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" , "ci" ]
  pull_request:
    branches: [ "master" , "ci" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Package project
      - name: package repository to zip
        run: |
          mkdir plugins 
          mv $GITHUB_WORKSPACE/* plugins
          
